kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: small
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: big
  resources:
    requests:
      storage: 8Gi