apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
  labels:
    type: nfs
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /var/data/nfs/pv-1
    server: 10.0.2.10
