apiVersion: v1
kind: Service
metadata:
  name: zk-nodeport
  labels:
    svc: expose
spec:
  type: NodePort
  selector:
    app: zk
  ports:
  - protocol: TCP
    nodePort: 32181
    port: 4888
    targetPort: 2181